import React, { Fragment } from 'react'
import MetaData from '../layout/MetaData'

const Privacy = () => {
    return (
        <Fragment>
            <MetaData title={'Privacy Policy'} />
            <div className="privacy-page">
                <h1>Privacy Policy</h1>
                <p>Armada Kemasan has created this privacy policy in order to demonstrate our firm commitment to your privacy. The following discloses our information gathering and dissemination practices relating to Armada Kemasan’s websites, mobile applications, the delivery of our services and other interactions with you (collectively, the “Sites”). Please note that this privacy policy only applies to those Sites that post a link to this privacy policy, and when you access any external links from Armada Kemasan’s Sites (including any Waste Management subsidiary Sites), such external websites may have different privacy policies from the Sites and Armada Kemasan is not responsible for the privacy practices of such external websites. We encourage you to read all privacy policies posted on the web sites that you visit.</p>
                <p>In addition to reading this privacy policy, please review our Terms of Use, which governs your use of the Sites and our services. If you do not agree to our Terms of Use and the collection, use and sharing of your information as detailed in this privacy policy, please do not access or otherwise use the Sites.</p>
                <ol>
                    <li><p>Personal Information Collection</p></li>
                    <p>Waste Management may collect personal information which is information that alone or in combination with other information could be used to identify you. This could include your name, telephone number, e-mail address, date of birth, and home or business and mailing address or other location from which you use our services from information you provide us through technology including when you access certain areas of the Waste Management Sites that require registration for certain services, or if you require more information about those services. If you decide to purchase our products or services, we and/or our third-party services providers may need to collect certain additional information, like your credit or debit card number and expiration date, bank routing and account number. We also collect photos and videos from cameras on our trucks to analyze the use and delivery of our services (i.e., to determine whether containers have been overfilled).</p>
                    <p>When you visit, use and interact with the Sites, we may receive certain information about your visit, use or interactions. For example, we may monitor the number of people that visit the Sites, peak hours of visits, which page(s) are visited, the domains our visitors come from (e.g., google.com, yahoo.com, etc.), and which browsers people use to access the Service (e.g., Chrome, Firefox, Microsoft Internet Explorer, etc.), broad geographical information, and navigation pattern. In particular, the following information is created and automatically logged in our systems:</p>
                    <p>Log data: Information that your browser automatically sends whenever you visit the Site (“log data”). Log data includes your Internet Protocol address, browser type and settings, the date and time of your request, and how you interacted with the Site.</p>
                    <p>Cookies: Please see the “How Waste Management Collects Personal Information” section below to learn more about how we use cookies.</p>
                    <p>Usage Information: We collect information about how you use our Sites, such as the types of content that you view or engage with, the features you use, the actions you take, and the time, frequency and duration of your activities.</p>
                    <p>Specialized Information. We may collect and store information (including personal information) locally on your device using mechanisms such as browser web storage (including HTML 5) and application data caches. Certain services may include a unique application number in connection with the installation of apps. This number and information, including, without limitation, operating system type and app version number may be sent to our service providers when you install, update or uninstall apps.</p>
                    <p>At other times, Armada Kemasan may collect information that cannot be used to identify you. For example, we may aggregate non-personal information about you and other customers who visit our Sites. Aggregated information will not contain any information that can be linked directly back to you.</p>
                    <li><p>How Armada Kemasan Collects Personal Information</p></li>
                    <p>Armada Kemasan collects personal information we receive from you and from other sources. Armada Kemasan collects your personal information in connection with our products and services we provide to you. We also may use any number of tools to collect information about you, your computer access points, mobile devices, and the web browser that you use to connect to our Sites or digital applications. For example, “cookies” are tiny text files that we place on your computer or mobile device when you visit our Sites. We may use cookies to personalize your interactions with our Sites. You do not have to accept our cookies and you may set your browser to restrict their use and you may delete them after they have been placed on your computer or mobile devices. If you do not accept or delete our cookies, some areas of our Sites may take more time to work, or may not function properly. Under the laws of certain countries, cookies may be served, as long as individuals have provided their consent, having been given clear and comprehensive information, in particular about the purposes for which their personal data will be processed. Effective consent may be provided by using your browser settings, as long as you take positive action. Before using Armada Kemasan Sites, you are advised to check your current browser settings to ensure that the settings reflect your consent for Armada Kemasan to place cookies on your devices.</p>
                </ol>
            </div>
        </Fragment>
    )
}

export default Privacy
